#loc = loc(unknown)
#loc1 = loc("/Users/paul/Lokal/Software/chemtrain-dev/chemtrain/deploy/exporter.py":128:31)
#loc2 = loc("/Users/paul/Lokal/Software/chemtrain-dev/examples/lennard_jones/export.py":28:15)
#loc3 = loc("/Users/paul/Lokal/Software/chemtrain-dev/examples/lennard_jones/export.py":70:4)
#loc4 = loc("position")
#loc5 = loc("species")
#loc6 = loc("ghost_mask")
#loc7 = loc("graph_args[0]")
#loc8 = loc("graph_args[1]")
#loc10 = loc("/Users/paul/Lokal/Software/chemtrain-dev/chemtrain/deploy/exporter.py":101:28)
#loc13 = loc("/Users/paul/Lokal/Software/chemtrain-dev/examples/lennard_jones/export.py":65:19)
#loc24 = loc("Exporter.export"(#loc1))
#loc25 = loc("main"(#loc2))
#loc26 = loc("<module>"(#loc3))
#loc28 = loc("Exporter._energy_fn"(#loc10))
#loc31 = loc("build_export_model.<locals>.LennardJonesExport.energy_fn"(#loc13))
#loc42 = loc(callsite(#loc25 at #loc26))
#loc44 = loc(callsite(#loc24 at #loc42))
#loc54 = loc(callsite(#loc28 at #loc44))
#loc61 = loc(callsite(#loc31 at #loc54))
#loc79 = loc("jit(_energy_fn)/jit(main)/integer_pow[y=1]"(#loc61))
#loc83 = loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) in_layouts=(None, None) out_layouts=(None, None, None, None) resource_env=None donated_invars=(False, False) name=safe_mask keep_unused=False inline=False]"(#loc61))
#loc88 = loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue, UnspecifiedValue) in_layouts=(None, None, None) out_layouts=(None, None) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61))
#loc89 = loc("jit(_energy_fn)/jit(main)/integer_pow[y=-2]"(#loc61))
#loc90 = loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue,) out_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) in_layouts=(None,) out_layouts=(None, None, None, None, None, None, None) resource_env=None donated_invars=(False,) name=nan_to_num keep_unused=False inline=False]"(#loc61))
#loc94 = loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue,) in_layouts=(None, None, None, None, None, None, None) out_layouts=(None,) resource_env=None donated_invars=(False, False, False, False, False, False, False) name=nan_to_num keep_unused=False inline=False]"(#loc61))
#loc97 = loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue,) in_layouts=(None, None, None) out_layouts=(None,) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61))
#loc98 = loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue,) in_layouts=(None, None, None, None, None) out_layouts=(None,) resource_env=None donated_invars=(False, False, False, False, False) name=safe_mask keep_unused=False inline=False]"(#loc61))
#loc102 = loc("jit(_energy_fn)/jit(main)/scatter-add[update_consts=() dimension_numbers=ScatterDimensionNumbers(update_window_dims=(1,), inserted_window_dims=(0,), scatter_dims_to_operand_dims=(0,)) indices_are_sorted=False unique_indices=False mode=GatherScatterMode.PROMISE_IN_BOUNDS]"(#loc61))
#loc104 = loc("jit(_energy_fn)/jit(main)/jvp(vmap(jit(safe_mask)))/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue, UnspecifiedValue) in_layouts=(None, None, None) out_layouts=(None, None) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61))
#loc114 = loc("jit(_energy_fn)/jit(main)/jvp(jit(nan_to_num))/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue, UnspecifiedValue) in_layouts=(None, None, None) out_layouts=(None, None) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61))
#loc118 = loc("jit(_energy_fn)/jit(main)/transpose(jvp(jit(nan_to_num)))/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue,) in_layouts=(None, None, None) out_layouts=(None,) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61))
#loc123 = loc("jit(_energy_fn)/jit(main)/transpose(jvp(vmap(jit(safe_mask))))/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue,) in_layouts=(None, None, None) out_layouts=(None,) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61))
module @jit__energy_fn attributes {jax.uses_shape_polymorphism = true, mhlo.num_partitions = 1 : i32, mhlo.num_replicas = 1 : i32} {
  func.func public @main(%arg0: tensor<?x3xf32> {mhlo.layout_mode = "default"} loc(unknown), %arg1: tensor<?xi32> {mhlo.layout_mode = "default"} loc(unknown), %arg2: tensor<?xi1> {mhlo.layout_mode = "default"} loc(unknown), %arg3: tensor<?xi32> {mhlo.layout_mode = "default"} loc(unknown), %arg4: tensor<?xi32> {mhlo.layout_mode = "default"} loc(unknown)) -> (tensor<?x3xf32> {jax.result_info = "[0]", mhlo.layout_mode = "default"}, tensor<f32> {jax.result_info = "[1]", mhlo.layout_mode = "default"}) {
    %0 = stablehlo.get_dimension_size %arg0, dim = 0 : (tensor<?x3xf32>) -> tensor<i32> loc(#loc46)
    %1 = stablehlo.get_dimension_size %arg1, dim = 0 : (tensor<?xi32>) -> tensor<i32> loc(#loc46)
    %2 = stablehlo.get_dimension_size %arg2, dim = 0 : (tensor<?xi1>) -> tensor<i32> loc(#loc46)
    %3 = stablehlo.get_dimension_size %arg3, dim = 0 : (tensor<?xi32>) -> tensor<i32> loc(#loc46)
    %4 = stablehlo.get_dimension_size %arg4, dim = 0 : (tensor<?xi32>) -> tensor<i32> loc(#loc46)
    %c = stablehlo.constant dense<1> : tensor<i32> loc(#loc)
    %5 = stablehlo.compare  GE, %0, %c,  SIGNED : (tensor<i32>, tensor<i32>) -> tensor<i1> loc(#loc47)
    stablehlo.custom_call @shape_assertion(%5, %0) {api_version = 2 : i32, error_message = "Input shapes do not match the polymorphic shapes specification. Expected value >= 1 for dimension variable 'n_atoms'. Using the following polymorphic shapes specifications: args[0].shape = (n_atoms, 3),args[1].shape = (n_atoms,),args[2].shape = (n_atoms,),args[3].shape = (graph_max_neighbors,),args[4].shape = (graph_max_neighbors,). Obtained dimension variables: 'n_atoms' = {0} from specification 'n_atoms' for dimension args[0].shape[0] (= {0}), . Please see https://jax.readthedocs.io/en/latest/export/shape_poly.html#shape-assertion-errors for more details.", has_side_effect = true} : (tensor<i1>, tensor<i32>) -> () loc(#loc48)
    %6 = stablehlo.compare  EQ, %1, %0,  SIGNED : (tensor<i32>, tensor<i32>) -> tensor<i1> loc(#loc49)
    stablehlo.custom_call @shape_assertion(%6, %1, %0) {api_version = 2 : i32, error_message = "Input shapes do not match the polymorphic shapes specification. Found inconsistency between dimension size args[1].shape[0] (= {0}) and the specification 'n_atoms' (= {1}). Using the following polymorphic shapes specifications: args[0].shape = (n_atoms, 3),args[1].shape = (n_atoms,),args[2].shape = (n_atoms,),args[3].shape = (graph_max_neighbors,),args[4].shape = (graph_max_neighbors,). Obtained dimension variables: 'n_atoms' = {1} from specification 'n_atoms' for dimension args[0].shape[0] (= {1}), . Please see https://jax.readthedocs.io/en/latest/export/shape_poly.html#shape-assertion-errors for more details.", has_side_effect = true} : (tensor<i1>, tensor<i32>, tensor<i32>) -> () loc(#loc50)
    %7 = stablehlo.compare  EQ, %2, %0,  SIGNED : (tensor<i32>, tensor<i32>) -> tensor<i1> loc(#loc49)
    stablehlo.custom_call @shape_assertion(%7, %2, %0) {api_version = 2 : i32, error_message = "Input shapes do not match the polymorphic shapes specification. Found inconsistency between dimension size args[2].shape[0] (= {0}) and the specification 'n_atoms' (= {1}). Using the following polymorphic shapes specifications: args[0].shape = (n_atoms, 3),args[1].shape = (n_atoms,),args[2].shape = (n_atoms,),args[3].shape = (graph_max_neighbors,),args[4].shape = (graph_max_neighbors,). Obtained dimension variables: 'n_atoms' = {1} from specification 'n_atoms' for dimension args[0].shape[0] (= {1}), . Please see https://jax.readthedocs.io/en/latest/export/shape_poly.html#shape-assertion-errors for more details.", has_side_effect = true} : (tensor<i1>, tensor<i32>, tensor<i32>) -> () loc(#loc51)
    %c_0 = stablehlo.constant dense<1> : tensor<i32> loc(#loc)
    %8 = stablehlo.compare  GE, %3, %c_0,  SIGNED : (tensor<i32>, tensor<i32>) -> tensor<i1> loc(#loc47)
    stablehlo.custom_call @shape_assertion(%8, %0, %3) {api_version = 2 : i32, error_message = "Input shapes do not match the polymorphic shapes specification. Expected value >= 1 for dimension variable 'graph_max_neighbors'. Using the following polymorphic shapes specifications: args[0].shape = (n_atoms, 3),args[1].shape = (n_atoms,),args[2].shape = (n_atoms,),args[3].shape = (graph_max_neighbors,),args[4].shape = (graph_max_neighbors,). Obtained dimension variables: 'n_atoms' = {0} from specification 'n_atoms' for dimension args[0].shape[0] (= {0}), 'graph_max_neighbors' = {1} from specification 'graph_max_neighbors' for dimension args[3].shape[0] (= {1}), . Please see https://jax.readthedocs.io/en/latest/export/shape_poly.html#shape-assertion-errors for more details.", has_side_effect = true} : (tensor<i1>, tensor<i32>, tensor<i32>) -> () loc(#loc52)
    %9 = stablehlo.compare  EQ, %4, %3,  SIGNED : (tensor<i32>, tensor<i32>) -> tensor<i1> loc(#loc49)
    stablehlo.custom_call @shape_assertion(%9, %4, %3, %0) {api_version = 2 : i32, error_message = "Input shapes do not match the polymorphic shapes specification. Found inconsistency between dimension size args[4].shape[0] (= {0}) and the specification 'graph_max_neighbors' (= {1}). Using the following polymorphic shapes specifications: args[0].shape = (n_atoms, 3),args[1].shape = (n_atoms,),args[2].shape = (n_atoms,),args[3].shape = (graph_max_neighbors,),args[4].shape = (graph_max_neighbors,). Obtained dimension variables: 'n_atoms' = {2} from specification 'n_atoms' for dimension args[0].shape[0] (= {2}), 'graph_max_neighbors' = {1} from specification 'graph_max_neighbors' for dimension args[3].shape[0] (= {1}), . Please see https://jax.readthedocs.io/en/latest/export/shape_poly.html#shape-assertion-errors for more details.", has_side_effect = true} : (tensor<i1>, tensor<i32>, tensor<i32>, tensor<i32>) -> () loc(#loc53)
    %10:2 = call @_wrapped_jax_export_main(%3, %0, %arg0, %arg1, %arg2, %arg3, %arg4) : (tensor<i32>, tensor<i32>, tensor<?x3xf32>, tensor<?xi32>, tensor<?xi1>, tensor<?xi32>, tensor<?xi32>) -> (tensor<?x3xf32>, tensor<f32>) loc(#loc)
    return %10#0, %10#1 : tensor<?x3xf32>, tensor<f32> loc(#loc)
  } loc(#loc)
  func.func private @_wrapped_jax_export_main(%arg0: tensor<i32> {jax.global_constant = "graph_max_neighbors", mhlo.layout_mode = "default"} loc(unknown), %arg1: tensor<i32> {jax.global_constant = "n_atoms", mhlo.layout_mode = "default"} loc(unknown), %arg2: tensor<?x3xf32> {mhlo.layout_mode = "default"} loc("position"), %arg3: tensor<?xi32> {mhlo.layout_mode = "default"} loc("species"), %arg4: tensor<?xi1> {mhlo.layout_mode = "default"} loc("ghost_mask"), %arg5: tensor<?xi32> {mhlo.layout_mode = "default"} loc("graph_args[0]"), %arg6: tensor<?xi32> {mhlo.layout_mode = "default"} loc("graph_args[1]")) -> (tensor<?x3xf32> {jax.result_info = "[0]", mhlo.layout_mode = "default"}, tensor<f32> {jax.result_info = "[1]", mhlo.layout_mode = "default"}) {
    %c = stablehlo.constant dense<1> : tensor<i32> loc(#loc66)
    %c_0 = stablehlo.constant dense<1> : tensor<1xi32> loc(#loc66)
    %0 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc66)
    %1 = stablehlo.concatenate %c_0, %0, dim = 0 : (tensor<1xi32>, tensor<1xi32>) -> tensor<2xi32> loc(#loc66)
    %2 = stablehlo.dynamic_broadcast_in_dim %arg5, %1, dims = [1] : (tensor<?xi32>, tensor<2xi32>) -> tensor<1x?xi32> loc(#loc66)
    %c_1 = stablehlo.constant dense<1> : tensor<i32> loc(#loc66)
    %c_2 = stablehlo.constant dense<1> : tensor<1xi32> loc(#loc66)
    %3 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc66)
    %4 = stablehlo.concatenate %c_2, %3, dim = 0 : (tensor<1xi32>, tensor<1xi32>) -> tensor<2xi32> loc(#loc66)
    %5 = stablehlo.dynamic_broadcast_in_dim %arg6, %4, dims = [1] : (tensor<?xi32>, tensor<2xi32>) -> tensor<1x?xi32> loc(#loc66)
    %6 = stablehlo.concatenate %2, %5, dim = 0 : (tensor<1x?xi32>, tensor<1x?xi32>) -> tensor<2x?xi32> loc(#loc67)
    %cst = stablehlo.constant dense<5.000000e+00> : tensor<f32> loc(#loc)
    %cst_3 = stablehlo.constant dense<2.000000e+00> : tensor<f32> loc(#loc)
    %7 = stablehlo.power %cst, %cst_3 : tensor<f32> loc(#loc127)
    %cst_4 = stablehlo.constant dense<4.000000e+00> : tensor<f32> loc(#loc)
    %cst_5 = stablehlo.constant dense<2.000000e+00> : tensor<f32> loc(#loc)
    %8 = stablehlo.power %cst_4, %cst_5 : tensor<f32> loc(#loc127)
    %c_6 = stablehlo.constant dense<0> : tensor<i32> loc(#loc)
    %9 = stablehlo.broadcast_in_dim %c_6, dims = [] : (tensor<i32>) -> tensor<1xi32> loc(#loc69)
    %c_7 = stablehlo.constant dense<1> : tensor<i32> loc(#loc70)
    %c_8 = stablehlo.constant dense<1> : tensor<1xi32> loc(#loc70)
    %10 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc70)
    %11 = stablehlo.concatenate %c_8, %10, dim = 0 : (tensor<1xi32>, tensor<1xi32>) -> tensor<2xi32> loc(#loc70)
    %12 = "stablehlo.dynamic_gather"(%6, %9, %11) <{dimension_numbers = #stablehlo.gather<offset_dims = [0], collapsed_slice_dims = [0], start_index_map = [0]>, indices_are_sorted = true}> : (tensor<2x?xi32>, tensor<1xi32>, tensor<2xi32>) -> tensor<?xi32> loc(#loc70)
    %13 = stablehlo.convert %arg1 : tensor<i32> loc(#loc71)
    %c_9 = stablehlo.constant dense<0> : tensor<i32> loc(#loc)
    %14 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc72)
    %15 = stablehlo.dynamic_broadcast_in_dim %c_9, %14, dims = [] : (tensor<i32>, tensor<1xi32>) -> tensor<?xi32> loc(#loc72)
    %16 = stablehlo.compare  LT, %12, %15,  SIGNED : (tensor<?xi32>, tensor<?xi32>) -> tensor<?xi1> loc(#loc72)
    %17 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc73)
    %18 = stablehlo.dynamic_broadcast_in_dim %13, %17, dims = [] : (tensor<i32>, tensor<1xi32>) -> tensor<?xi32> loc(#loc73)
    %19 = stablehlo.add %12, %18 : tensor<?xi32> loc(#loc73)
    %20 = stablehlo.select %16, %19, %12 : tensor<?xi1>, tensor<?xi32> loc(#loc74)
    %c_10 = stablehlo.constant dense<1> : tensor<i32> loc(#loc75)
    %21 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc75)
    %c_11 = stablehlo.constant dense<1> : tensor<1xi32> loc(#loc75)
    %22 = stablehlo.concatenate %21, %c_11, dim = 0 : (tensor<1xi32>, tensor<1xi32>) -> tensor<2xi32> loc(#loc75)
    %23 = stablehlo.dynamic_broadcast_in_dim %20, %22, dims = [0] : (tensor<?xi32>, tensor<2xi32>) -> tensor<?x1xi32> loc(#loc75)
    %24 = "stablehlo.gather"(%arg2, %23) <{dimension_numbers = #stablehlo.gather<offset_dims = [1], collapsed_slice_dims = [0], start_index_map = [0], index_vector_dim = 1>, slice_sizes = array<i64: 1, 3>}> : (tensor<?x3xf32>, tensor<?x1xi32>) -> tensor<?x3xf32> loc(#loc76)
    %c_12 = stablehlo.constant dense<1> : tensor<i32> loc(#loc)
    %25 = stablehlo.broadcast_in_dim %c_12, dims = [] : (tensor<i32>) -> tensor<1xi32> loc(#loc69)
    %c_13 = stablehlo.constant dense<1> : tensor<i32> loc(#loc70)
    %c_14 = stablehlo.constant dense<1> : tensor<1xi32> loc(#loc70)
    %26 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc70)
    %27 = stablehlo.concatenate %c_14, %26, dim = 0 : (tensor<1xi32>, tensor<1xi32>) -> tensor<2xi32> loc(#loc70)
    %28 = "stablehlo.dynamic_gather"(%6, %25, %27) <{dimension_numbers = #stablehlo.gather<offset_dims = [0], collapsed_slice_dims = [0], start_index_map = [0]>, indices_are_sorted = true}> : (tensor<2x?xi32>, tensor<1xi32>, tensor<2xi32>) -> tensor<?xi32> loc(#loc70)
    %29 = stablehlo.convert %arg1 : tensor<i32> loc(#loc71)
    %c_15 = stablehlo.constant dense<0> : tensor<i32> loc(#loc)
    %30 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc72)
    %31 = stablehlo.dynamic_broadcast_in_dim %c_15, %30, dims = [] : (tensor<i32>, tensor<1xi32>) -> tensor<?xi32> loc(#loc72)
    %32 = stablehlo.compare  LT, %28, %31,  SIGNED : (tensor<?xi32>, tensor<?xi32>) -> tensor<?xi1> loc(#loc72)
    %33 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc73)
    %34 = stablehlo.dynamic_broadcast_in_dim %29, %33, dims = [] : (tensor<i32>, tensor<1xi32>) -> tensor<?xi32> loc(#loc73)
    %35 = stablehlo.add %28, %34 : tensor<?xi32> loc(#loc73)
    %36 = stablehlo.select %32, %35, %28 : tensor<?xi1>, tensor<?xi32> loc(#loc74)
    %c_16 = stablehlo.constant dense<1> : tensor<i32> loc(#loc75)
    %37 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc75)
    %c_17 = stablehlo.constant dense<1> : tensor<1xi32> loc(#loc75)
    %38 = stablehlo.concatenate %37, %c_17, dim = 0 : (tensor<1xi32>, tensor<1xi32>) -> tensor<2xi32> loc(#loc75)
    %39 = stablehlo.dynamic_broadcast_in_dim %36, %38, dims = [0] : (tensor<?xi32>, tensor<2xi32>) -> tensor<?x1xi32> loc(#loc75)
    %40 = "stablehlo.gather"(%arg2, %39) <{dimension_numbers = #stablehlo.gather<offset_dims = [1], collapsed_slice_dims = [0], start_index_map = [0], index_vector_dim = 1>, slice_sizes = array<i64: 1, 3>}> : (tensor<?x3xf32>, tensor<?x1xi32>) -> tensor<?x3xf32> loc(#loc76)
    %41 = stablehlo.subtract %40, %24 : tensor<?x3xf32> loc(#loc128)
    %42 = stablehlo.multiply %41, %41 : tensor<?x3xf32> loc(#loc78)
    %43 = call @integer_pow(%arg0, %arg1, %41) : (tensor<i32>, tensor<i32>, tensor<?x3xf32>) -> tensor<?x3xf32> loc(#loc79)
    %cst_18 = stablehlo.constant dense<2.000000e+00> : tensor<f32> loc(#loc)
    %c_19 = stablehlo.constant dense<3> : tensor<i32> loc(#loc80)
    %44 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc80)
    %c_20 = stablehlo.constant dense<3> : tensor<1xi32> loc(#loc80)
    %45 = stablehlo.concatenate %44, %c_20, dim = 0 : (tensor<1xi32>, tensor<1xi32>) -> tensor<2xi32> loc(#loc80)
    %46 = stablehlo.dynamic_broadcast_in_dim %cst_18, %45, dims = [] : (tensor<f32>, tensor<2xi32>) -> tensor<?x3xf32> loc(#loc80)
    %47 = stablehlo.multiply %46, %43 : tensor<?x3xf32> loc(#loc80)
    %cst_21 = stablehlo.constant dense<0.000000e+00> : tensor<f32> loc(#loc81)
    %48 = stablehlo.reduce(%42 init: %cst_21) applies stablehlo.add across dimensions = [1] : (tensor<?x3xf32>, tensor<f32>) -> tensor<?xf32> loc(#loc81)
    %cst_22 = stablehlo.constant dense<0.000000e+00> : tensor<f32> loc(#loc)
    %49 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc82)
    %50 = stablehlo.dynamic_broadcast_in_dim %cst_22, %49, dims = [] : (tensor<f32>, tensor<1xi32>) -> tensor<?xf32> loc(#loc82)
    %51 = stablehlo.compare  GT, %48, %50,  FLOAT : (tensor<?xf32>, tensor<?xf32>) -> tensor<?xi1> loc(#loc82)
    %52:4 = call @safe_mask(%arg0, %arg1, %51, %48) : (tensor<i32>, tensor<i32>, tensor<?xi1>, tensor<?xf32>) -> (tensor<?xf32>, tensor<?xf32>, tensor<?xf32>, tensor<?xf32>) loc(#loc83)
    %c_23 = stablehlo.constant dense<0> : tensor<i32> loc(#loc)
    %53 = stablehlo.broadcast_in_dim %c_23, dims = [] : (tensor<i32>) -> tensor<1xi32> loc(#loc69)
    %c_24 = stablehlo.constant dense<1> : tensor<i32> loc(#loc70)
    %c_25 = stablehlo.constant dense<1> : tensor<1xi32> loc(#loc70)
    %54 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc70)
    %55 = stablehlo.concatenate %c_25, %54, dim = 0 : (tensor<1xi32>, tensor<1xi32>) -> tensor<2xi32> loc(#loc70)
    %56 = "stablehlo.dynamic_gather"(%6, %53, %55) <{dimension_numbers = #stablehlo.gather<offset_dims = [0], collapsed_slice_dims = [0], start_index_map = [0]>, indices_are_sorted = true}> : (tensor<2x?xi32>, tensor<1xi32>, tensor<2xi32>) -> tensor<?xi32> loc(#loc70)
    %57 = stablehlo.convert %arg1 : tensor<i32> loc(#loc71)
    %58 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc72)
    %59 = stablehlo.dynamic_broadcast_in_dim %57, %58, dims = [] : (tensor<i32>, tensor<1xi32>) -> tensor<?xi32> loc(#loc72)
    %60 = stablehlo.compare  LT, %56, %59,  SIGNED : (tensor<?xi32>, tensor<?xi32>) -> tensor<?xi1> loc(#loc72)
    %cst_26 = stablehlo.constant dense<2.000000e+00> : tensor<f32> loc(#loc)
    %61 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc84)
    %62 = stablehlo.dynamic_broadcast_in_dim %cst_26, %61, dims = [] : (tensor<f32>, tensor<1xi32>) -> tensor<?xf32> loc(#loc84)
    %63 = stablehlo.power %52#0, %62 : tensor<?xf32> loc(#loc84)
    %cst_27 = stablehlo.constant dense<2.000000e+00> : tensor<f32> loc(#loc)
    %cst_28 = stablehlo.constant dense<1.000000e+00> : tensor<f32> loc(#loc)
    %64 = stablehlo.subtract %cst_27, %cst_28 : tensor<f32> loc(#loc85)
    %65 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc84)
    %66 = stablehlo.dynamic_broadcast_in_dim %64, %65, dims = [] : (tensor<f32>, tensor<1xi32>) -> tensor<?xf32> loc(#loc84)
    %67 = stablehlo.power %52#0, %66 : tensor<?xf32> loc(#loc84)
    %cst_29 = stablehlo.constant dense<2.000000e+00> : tensor<f32> loc(#loc)
    %68 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc80)
    %69 = stablehlo.dynamic_broadcast_in_dim %cst_29, %68, dims = [] : (tensor<f32>, tensor<1xi32>) -> tensor<?xf32> loc(#loc80)
    %70 = stablehlo.multiply %69, %67 : tensor<?xf32> loc(#loc80)
    %cst_30 = stablehlo.constant dense<5.000000e+00> : tensor<f32> loc(#loc)
    %71 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc72)
    %72 = stablehlo.dynamic_broadcast_in_dim %cst_30, %71, dims = [] : (tensor<f32>, tensor<1xi32>) -> tensor<?xf32> loc(#loc72)
    %73 = stablehlo.compare  LT, %52#0, %72,  FLOAT : (tensor<?xf32>, tensor<?xf32>) -> tensor<?xi1> loc(#loc72)
    %74 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc85)
    %75 = stablehlo.dynamic_broadcast_in_dim %7, %74, dims = [] : (tensor<f32>, tensor<1xi32>) -> tensor<?xf32> loc(#loc85)
    %76 = stablehlo.subtract %75, %63 : tensor<?xf32> loc(#loc85)
    %77 = stablehlo.multiply %76, %76 : tensor<?xf32> loc(#loc78)
    %78 = call @integer_pow_0(%arg0, %arg1, %76) : (tensor<i32>, tensor<i32>, tensor<?xf32>) -> tensor<?xf32> loc(#loc79)
    %cst_31 = stablehlo.constant dense<2.000000e+00> : tensor<f32> loc(#loc)
    %79 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc80)
    %80 = stablehlo.dynamic_broadcast_in_dim %cst_31, %79, dims = [] : (tensor<f32>, tensor<1xi32>) -> tensor<?xf32> loc(#loc80)
    %81 = stablehlo.multiply %80, %78 : tensor<?xf32> loc(#loc80)
    %cst_32 = stablehlo.constant dense<2.000000e+00> : tensor<f32> loc(#loc)
    %82 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc80)
    %83 = stablehlo.dynamic_broadcast_in_dim %cst_32, %82, dims = [] : (tensor<f32>, tensor<1xi32>) -> tensor<?xf32> loc(#loc80)
    %84 = stablehlo.multiply %83, %63 : tensor<?xf32> loc(#loc80)
    %85 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc73)
    %86 = stablehlo.dynamic_broadcast_in_dim %7, %85, dims = [] : (tensor<f32>, tensor<1xi32>) -> tensor<?xf32> loc(#loc73)
    %87 = stablehlo.add %86, %84 : tensor<?xf32> loc(#loc73)
    %cst_33 = stablehlo.constant dense<3.000000e+00> : tensor<f32> loc(#loc)
    %88 = stablehlo.multiply %cst_33, %8 : tensor<f32> loc(#loc80)
    %89 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc85)
    %90 = stablehlo.dynamic_broadcast_in_dim %88, %89, dims = [] : (tensor<f32>, tensor<1xi32>) -> tensor<?xf32> loc(#loc85)
    %91 = stablehlo.subtract %87, %90 : tensor<?xf32> loc(#loc85)
    %92 = stablehlo.multiply %77, %91 : tensor<?xf32> loc(#loc80)
    %93 = stablehlo.subtract %7, %8 : tensor<f32> loc(#loc85)
    %94 = stablehlo.multiply %93, %93 : tensor<f32> loc(#loc86)
    %95 = stablehlo.multiply %94, %93 : tensor<f32> loc(#loc86)
    %96 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc87)
    %97 = stablehlo.dynamic_broadcast_in_dim %95, %96, dims = [] : (tensor<f32>, tensor<1xi32>) -> tensor<?xf32> loc(#loc87)
    %98 = stablehlo.divide %92, %97 : tensor<?xf32> loc(#loc87)
    %c_34 = stablehlo.constant dense<0> : tensor<i32> loc(#loc)
    %99:2 = call @_where_1(%arg0, %arg1, %73, %98, %c_34) : (tensor<i32>, tensor<i32>, tensor<?xi1>, tensor<?xf32>, tensor<i32>) -> (tensor<?xf32>, tensor<?xf32>) loc(#loc88)
    %cst_35 = stablehlo.constant dense<4.000000e+00> : tensor<f32> loc(#loc)
    %100 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc72)
    %101 = stablehlo.dynamic_broadcast_in_dim %cst_35, %100, dims = [] : (tensor<f32>, tensor<1xi32>) -> tensor<?xf32> loc(#loc72)
    %102 = stablehlo.compare  LT, %52#0, %101,  FLOAT : (tensor<?xf32>, tensor<?xf32>) -> tensor<?xi1> loc(#loc72)
    %c_36 = stablehlo.constant dense<1> : tensor<i32> loc(#loc)
    %103:2 = call @_where_2(%arg0, %arg1, %102, %c_36, %99#0) : (tensor<i32>, tensor<i32>, tensor<?xi1>, tensor<i32>, tensor<?xf32>) -> (tensor<?xf32>, tensor<?xf32>) loc(#loc88)
    %cst_37 = stablehlo.constant dense<3.165000e+00> : tensor<f32> loc(#loc)
    %104 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc87)
    %105 = stablehlo.dynamic_broadcast_in_dim %cst_37, %104, dims = [] : (tensor<f32>, tensor<1xi32>) -> tensor<?xf32> loc(#loc87)
    %106 = stablehlo.divide %105, %52#0 : tensor<?xf32> loc(#loc87)
    %107 = call @integer_pow_3(%arg0, %arg1, %52#0) : (tensor<i32>, tensor<i32>, tensor<?xf32>) -> tensor<?xf32> loc(#loc89)
    %108 = stablehlo.multiply %106, %106 : tensor<?xf32> loc(#loc80)
    %109 = stablehlo.multiply %108, %108 : tensor<?xf32> loc(#loc80)
    %110 = stablehlo.multiply %109, %108 : tensor<?xf32> loc(#loc80)
    %111 = stablehlo.multiply %110, %110 : tensor<?xf32> loc(#loc80)
    %cst_38 = stablehlo.constant dense<4.000000e+00> : tensor<f32> loc(#loc)
    %cst_39 = stablehlo.constant dense<1.000000e+00> : tensor<f32> loc(#loc)
    %112 = stablehlo.multiply %cst_38, %cst_39 : tensor<f32> loc(#loc80)
    %113 = stablehlo.subtract %111, %110 : tensor<?xf32> loc(#loc85)
    %114 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc80)
    %115 = stablehlo.dynamic_broadcast_in_dim %112, %114, dims = [] : (tensor<f32>, tensor<1xi32>) -> tensor<?xf32> loc(#loc80)
    %116 = stablehlo.multiply %115, %113 : tensor<?xf32> loc(#loc80)
    %117:7 = call @nan_to_num(%arg0, %arg1, %116) : (tensor<i32>, tensor<i32>, tensor<?xf32>) -> (tensor<?xf32>, tensor<?xi1>, tensor<?xf32>, tensor<?xi1>, tensor<?xf32>, tensor<?xi1>, tensor<?xf32>) loc(#loc90)
    %118 = stablehlo.multiply %103#0, %117#0 : tensor<?xf32> loc(#loc80)
    %119 = stablehlo.convert %60 : (tensor<?xi1>) -> tensor<?xf32> loc(#loc91)
    %120 = stablehlo.multiply %118, %119 : tensor<?xf32> loc(#loc80)
    %cst_40 = stablehlo.constant dense<0.000000e+00> : tensor<f32> loc(#loc92)
    %121 = stablehlo.reduce(%120 init: %cst_40) applies stablehlo.add across dimensions = [0] : (tensor<?xf32>, tensor<f32>) -> tensor<f32> loc(#loc92)
    %cst_41 = stablehlo.constant dense<2.000000e+00> : tensor<f32> loc(#loc)
    %122 = stablehlo.divide %121, %cst_41 : tensor<f32> loc(#loc87)
    %cst_42 = stablehlo.constant dense<0.000000e+00> : tensor<f32> loc(#loc62)
    %123 = stablehlo.reduce(%122 init: %cst_42) applies stablehlo.add across dimensions = [] : (tensor<f32>, tensor<f32>) -> tensor<f32> loc(#loc62)
    %124 = stablehlo.negate %123 : tensor<f32> loc(#loc63)
    %cst_43 = stablehlo.constant dense<0.000000e+00> : tensor<f32> loc(#loc64)
    %125 = stablehlo.reduce(%122 init: %cst_43) applies stablehlo.add across dimensions = [] : (tensor<f32>, tensor<f32>) -> tensor<f32> loc(#loc64)
    %cst_44 = stablehlo.constant dense<1.000000e+00> : tensor<f32> loc(#loc)
    %126 = stablehlo.negate %cst_44 : tensor<f32> loc(#loc63)
    %cst_45 = stablehlo.constant dense<2.000000e+00> : tensor<f32> loc(#loc)
    %127 = stablehlo.divide %126, %cst_45 : tensor<f32> loc(#loc87)
    %128 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc93)
    %129 = stablehlo.dynamic_broadcast_in_dim %127, %128, dims = [] : (tensor<f32>, tensor<1xi32>) -> tensor<?xf32> loc(#loc93)
    %130 = stablehlo.multiply %129, %119 : tensor<?xf32> loc(#loc80)
    %131 = stablehlo.multiply %103#0, %130 : tensor<?xf32> loc(#loc80)
    %132 = stablehlo.multiply %130, %117#0 : tensor<?xf32> loc(#loc80)
    %133 = call @nan_to_num_5(%arg0, %arg1, %117#1, %117#2, %117#3, %117#4, %117#5, %117#6, %131) : (tensor<i32>, tensor<i32>, tensor<?xi1>, tensor<?xf32>, tensor<?xi1>, tensor<?xf32>, tensor<?xi1>, tensor<?xf32>, tensor<?xf32>) -> tensor<?xf32> loc(#loc94)
    %134 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc80)
    %135 = stablehlo.dynamic_broadcast_in_dim %112, %134, dims = [] : (tensor<f32>, tensor<1xi32>) -> tensor<?xf32> loc(#loc80)
    %136 = stablehlo.multiply %135, %133 : tensor<?xf32> loc(#loc80)
    %137 = stablehlo.negate %136 : tensor<?xf32> loc(#loc95)
    %138 = stablehlo.multiply %110, %136 : tensor<?xf32> loc(#loc80)
    %139 = stablehlo.multiply %136, %110 : tensor<?xf32> loc(#loc80)
    %140 = stablehlo.add %137, %139 : tensor<?xf32> loc(#loc96)
    %141 = stablehlo.add %140, %138 : tensor<?xf32> loc(#loc96)
    %142 = stablehlo.multiply %109, %141 : tensor<?xf32> loc(#loc80)
    %143 = stablehlo.multiply %141, %108 : tensor<?xf32> loc(#loc80)
    %144 = stablehlo.multiply %108, %143 : tensor<?xf32> loc(#loc80)
    %145 = stablehlo.multiply %143, %108 : tensor<?xf32> loc(#loc80)
    %146 = stablehlo.add %142, %145 : tensor<?xf32> loc(#loc96)
    %147 = stablehlo.add %146, %144 : tensor<?xf32> loc(#loc96)
    %148 = stablehlo.multiply %106, %147 : tensor<?xf32> loc(#loc80)
    %149 = stablehlo.multiply %147, %106 : tensor<?xf32> loc(#loc80)
    %150 = stablehlo.add %149, %148 : tensor<?xf32> loc(#loc96)
    %151 = stablehlo.multiply %150, %107 : tensor<?xf32> loc(#loc80)
    %cst_46 = stablehlo.constant dense<3.165000e+00> : tensor<f32> loc(#loc)
    %152 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc80)
    %153 = stablehlo.dynamic_broadcast_in_dim %cst_46, %152, dims = [] : (tensor<f32>, tensor<1xi32>) -> tensor<?xf32> loc(#loc80)
    %154 = stablehlo.multiply %151, %153 : tensor<?xf32> loc(#loc80)
    %155 = stablehlo.negate %154 : tensor<?xf32> loc(#loc95)
    %156 = call @_where_7(%arg0, %arg1, %102, %103#1, %132) : (tensor<i32>, tensor<i32>, tensor<?xi1>, tensor<?xf32>, tensor<?xf32>) -> tensor<?xf32> loc(#loc97)
    %157 = call @_where_8(%arg0, %arg1, %73, %99#1, %156) : (tensor<i32>, tensor<i32>, tensor<?xi1>, tensor<?xf32>, tensor<?xf32>) -> tensor<?xf32> loc(#loc97)
    %158 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc87)
    %159 = stablehlo.dynamic_broadcast_in_dim %95, %158, dims = [] : (tensor<f32>, tensor<1xi32>) -> tensor<?xf32> loc(#loc87)
    %160 = stablehlo.divide %157, %159 : tensor<?xf32> loc(#loc87)
    %161 = stablehlo.multiply %77, %160 : tensor<?xf32> loc(#loc80)
    %162 = stablehlo.multiply %160, %91 : tensor<?xf32> loc(#loc80)
    %cst_47 = stablehlo.constant dense<2.000000e+00> : tensor<f32> loc(#loc)
    %163 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc80)
    %164 = stablehlo.dynamic_broadcast_in_dim %cst_47, %163, dims = [] : (tensor<f32>, tensor<1xi32>) -> tensor<?xf32> loc(#loc80)
    %165 = stablehlo.multiply %164, %161 : tensor<?xf32> loc(#loc80)
    %166 = stablehlo.multiply %162, %81 : tensor<?xf32> loc(#loc80)
    %167 = stablehlo.negate %166 : tensor<?xf32> loc(#loc95)
    %168 = stablehlo.add %165, %167 : tensor<?xf32> loc(#loc96)
    %169 = stablehlo.multiply %168, %70 : tensor<?xf32> loc(#loc80)
    %170 = stablehlo.add %155, %169 : tensor<?xf32> loc(#loc96)
    %171 = call @safe_mask_9(%arg0, %arg1, %51, %52#1, %52#2, %52#3, %170) : (tensor<i32>, tensor<i32>, tensor<?xi1>, tensor<?xf32>, tensor<?xf32>, tensor<?xf32>, tensor<?xf32>) -> tensor<?xf32> loc(#loc98)
    %c_48 = stablehlo.constant dense<3> : tensor<i32> loc(#loc99)
    %172 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc99)
    %c_49 = stablehlo.constant dense<3> : tensor<1xi32> loc(#loc99)
    %173 = stablehlo.concatenate %172, %c_49, dim = 0 : (tensor<1xi32>, tensor<1xi32>) -> tensor<2xi32> loc(#loc99)
    %174 = stablehlo.dynamic_broadcast_in_dim %171, %173, dims = [0] : (tensor<?xf32>, tensor<2xi32>) -> tensor<?x3xf32> loc(#loc99)
    %175 = stablehlo.multiply %174, %47 : tensor<?x3xf32> loc(#loc80)
    %176 = stablehlo.negate %175 : tensor<?x3xf32> loc(#loc129)
    %cst_50 = stablehlo.constant dense<0.000000e+00> : tensor<f32> loc(#loc100)
    %177 = stablehlo.reduce(%176 init: %cst_50) applies stablehlo.add across dimensions = [] : (tensor<?x3xf32>, tensor<f32>) -> tensor<?x3xf32> loc(#loc100)
    %cst_51 = stablehlo.constant dense<0.000000e+00> : tensor<f32> loc(#loc)
    %c_52 = stablehlo.constant dense<3> : tensor<i32> loc(#loc101)
    %178 = stablehlo.reshape %arg1 : (tensor<i32>) -> tensor<1xi32> loc(#loc101)
    %c_53 = stablehlo.constant dense<3> : tensor<1xi32> loc(#loc101)
    %179 = stablehlo.concatenate %178, %c_53, dim = 0 : (tensor<1xi32>, tensor<1xi32>) -> tensor<2xi32> loc(#loc101)
    %180 = stablehlo.dynamic_broadcast_in_dim %cst_51, %179, dims = [] : (tensor<f32>, tensor<2xi32>) -> tensor<?x3xf32> loc(#loc101)
    %181 = "stablehlo.scatter"(%180, %23, %177) <{scatter_dimension_numbers = #stablehlo.scatter<update_window_dims = [1], inserted_window_dims = [0], scatter_dims_to_operand_dims = [0], index_vector_dim = 1>}> ({
    ^bb0(%arg7: tensor<f32> loc("jit(_energy_fn)/jit(main)/scatter-add[update_consts=() dimension_numbers=ScatterDimensionNumbers(update_window_dims=(1,), inserted_window_dims=(0,), scatter_dims_to_operand_dims=(0,)) indices_are_sorted=False unique_indices=False mode=GatherScatterMode.PROMISE_IN_BOUNDS]"(#loc61)), %arg8: tensor<f32> loc("jit(_energy_fn)/jit(main)/scatter-add[update_consts=() dimension_numbers=ScatterDimensionNumbers(update_window_dims=(1,), inserted_window_dims=(0,), scatter_dims_to_operand_dims=(0,)) indices_are_sorted=False unique_indices=False mode=GatherScatterMode.PROMISE_IN_BOUNDS]"(#loc61))):
      %188 = stablehlo.add %arg7, %arg8 : tensor<f32> loc(#loc134)
      stablehlo.return %188 : tensor<f32> loc(#loc102)
    }) : (tensor<?x3xf32>, tensor<?x1xi32>, tensor<?x3xf32>) -> tensor<?x3xf32> loc(#loc102)
    %cst_54 = stablehlo.constant dense<0.000000e+00> : tensor<f32> loc(#loc100)
    %182 = stablehlo.reduce(%175 init: %cst_54) applies stablehlo.add across dimensions = [] : (tensor<?x3xf32>, tensor<f32>) -> tensor<?x3xf32> loc(#loc100)
    %cst_55 = stablehlo.constant dense<0.000000e+00> : tensor<f32> loc(#loc)
    %c_56 = stablehlo.constant dense<3> : tensor<i32> loc(#loc101)
    %183 = stablehlo.reshape %arg1 : (tensor<i32>) -> tensor<1xi32> loc(#loc101)
    %c_57 = stablehlo.constant dense<3> : tensor<1xi32> loc(#loc101)
    %184 = stablehlo.concatenate %183, %c_57, dim = 0 : (tensor<1xi32>, tensor<1xi32>) -> tensor<2xi32> loc(#loc101)
    %185 = stablehlo.dynamic_broadcast_in_dim %cst_55, %184, dims = [] : (tensor<f32>, tensor<2xi32>) -> tensor<?x3xf32> loc(#loc101)
    %186 = "stablehlo.scatter"(%185, %39, %182) <{scatter_dimension_numbers = #stablehlo.scatter<update_window_dims = [1], inserted_window_dims = [0], scatter_dims_to_operand_dims = [0], index_vector_dim = 1>}> ({
    ^bb0(%arg7: tensor<f32> loc("jit(_energy_fn)/jit(main)/scatter-add[update_consts=() dimension_numbers=ScatterDimensionNumbers(update_window_dims=(1,), inserted_window_dims=(0,), scatter_dims_to_operand_dims=(0,)) indices_are_sorted=False unique_indices=False mode=GatherScatterMode.PROMISE_IN_BOUNDS]"(#loc61)), %arg8: tensor<f32> loc("jit(_energy_fn)/jit(main)/scatter-add[update_consts=() dimension_numbers=ScatterDimensionNumbers(update_window_dims=(1,), inserted_window_dims=(0,), scatter_dims_to_operand_dims=(0,)) indices_are_sorted=False unique_indices=False mode=GatherScatterMode.PROMISE_IN_BOUNDS]"(#loc61))):
      %188 = stablehlo.add %arg7, %arg8 : tensor<f32> loc(#loc134)
      stablehlo.return %188 : tensor<f32> loc(#loc102)
    }) : (tensor<?x3xf32>, tensor<?x1xi32>, tensor<?x3xf32>) -> tensor<?x3xf32> loc(#loc102)
    %187 = stablehlo.add %181, %186 : tensor<?x3xf32> loc(#loc96)
    return %187, %125 : tensor<?x3xf32>, tensor<f32> loc(#loc)
  } loc(#loc)
  func.func private @integer_pow(%arg0: tensor<i32> loc("jit(_energy_fn)/jit(main)/integer_pow[y=1]"(#loc61)), %arg1: tensor<i32> loc("jit(_energy_fn)/jit(main)/integer_pow[y=1]"(#loc61)), %arg2: tensor<?x3xf32> loc("jit(_energy_fn)/jit(main)/integer_pow[y=1]"(#loc61))) -> tensor<?x3xf32> {
    return %arg2 : tensor<?x3xf32> loc(#loc79)
  } loc(#loc79)
  func.func private @safe_mask(%arg0: tensor<i32> {jax.global_constant = "graph_max_neighbors", mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) in_layouts=(None, None) out_layouts=(None, None, None, None) resource_env=None donated_invars=(False, False) name=safe_mask keep_unused=False inline=False]"(#loc61)), %arg1: tensor<i32> {jax.global_constant = "n_atoms", mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) in_layouts=(None, None) out_layouts=(None, None, None, None) resource_env=None donated_invars=(False, False) name=safe_mask keep_unused=False inline=False]"(#loc61)), %arg2: tensor<?xi1> {mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) in_layouts=(None, None) out_layouts=(None, None, None, None) resource_env=None donated_invars=(False, False) name=safe_mask keep_unused=False inline=False]"(#loc61)), %arg3: tensor<?xf32> {mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) in_layouts=(None, None) out_layouts=(None, None, None, None) resource_env=None donated_invars=(False, False) name=safe_mask keep_unused=False inline=False]"(#loc61))) -> (tensor<?xf32> {mhlo.layout_mode = "default"}, tensor<?xf32> {mhlo.layout_mode = "default"}, tensor<?xf32> {mhlo.layout_mode = "default"}, tensor<?xf32> {mhlo.layout_mode = "default"}) {
    %c = stablehlo.constant dense<0> : tensor<i32> loc(#loc83)
    %0:2 = call @_where(%arg0, %arg1, %arg2, %arg3, %c) : (tensor<i32>, tensor<i32>, tensor<?xi1>, tensor<?xf32>, tensor<i32>) -> (tensor<?xf32>, tensor<?xf32>) loc(#loc104)
    %1 = stablehlo.sqrt %0#0 : tensor<?xf32> loc(#loc105)
    %cst = stablehlo.constant dense<5.000000e-01> : tensor<f32> loc(#loc83)
    %2 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc106)
    %3 = stablehlo.dynamic_broadcast_in_dim %cst, %2, dims = [] : (tensor<f32>, tensor<1xi32>) -> tensor<?xf32> loc(#loc106)
    %4 = stablehlo.divide %3, %1 : tensor<?xf32> loc(#loc106)
    %c_0 = stablehlo.constant dense<0> : tensor<i32> loc(#loc83)
    %5:2 = call @_where(%arg0, %arg1, %arg2, %1, %c_0) : (tensor<i32>, tensor<i32>, tensor<?xi1>, tensor<?xf32>, tensor<i32>) -> (tensor<?xf32>, tensor<?xf32>) loc(#loc104)
    return %5#0, %0#1, %4, %5#1 : tensor<?xf32>, tensor<?xf32>, tensor<?xf32>, tensor<?xf32> loc(#loc83)
  } loc(#loc83)
  func.func private @_where(%arg0: tensor<i32> {jax.global_constant = "graph_max_neighbors", mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/jvp(vmap(jit(safe_mask)))/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue, UnspecifiedValue) in_layouts=(None, None, None) out_layouts=(None, None) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61)), %arg1: tensor<i32> {jax.global_constant = "n_atoms", mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/jvp(vmap(jit(safe_mask)))/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue, UnspecifiedValue) in_layouts=(None, None, None) out_layouts=(None, None) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61)), %arg2: tensor<?xi1> {mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/jvp(vmap(jit(safe_mask)))/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue, UnspecifiedValue) in_layouts=(None, None, None) out_layouts=(None, None) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61)), %arg3: tensor<?xf32> {mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/jvp(vmap(jit(safe_mask)))/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue, UnspecifiedValue) in_layouts=(None, None, None) out_layouts=(None, None) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61)), %arg4: tensor<i32> {mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/jvp(vmap(jit(safe_mask)))/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue, UnspecifiedValue) in_layouts=(None, None, None) out_layouts=(None, None) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61))) -> (tensor<?xf32> {mhlo.layout_mode = "default"}, tensor<?xf32> {mhlo.layout_mode = "default"}) {
    %0 = stablehlo.convert %arg4 : (tensor<i32>) -> tensor<f32> loc(#loc107)
    %1 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc108)
    %2 = stablehlo.dynamic_broadcast_in_dim %0, %1, dims = [] : (tensor<f32>, tensor<1xi32>) -> tensor<?xf32> loc(#loc108)
    %3 = stablehlo.select %arg2, %arg3, %2 : tensor<?xi1>, tensor<?xf32> loc(#loc109)
    %cst = stablehlo.constant dense<0.000000e+00> : tensor<f32> loc(#loc104)
    %4 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc108)
    %5 = stablehlo.dynamic_broadcast_in_dim %cst, %4, dims = [] : (tensor<f32>, tensor<1xi32>) -> tensor<?xf32> loc(#loc108)
    return %3, %5 : tensor<?xf32>, tensor<?xf32> loc(#loc104)
  } loc(#loc104)
  func.func private @integer_pow_0(%arg0: tensor<i32> loc("jit(_energy_fn)/jit(main)/integer_pow[y=1]"(#loc61)), %arg1: tensor<i32> loc("jit(_energy_fn)/jit(main)/integer_pow[y=1]"(#loc61)), %arg2: tensor<?xf32> loc("jit(_energy_fn)/jit(main)/integer_pow[y=1]"(#loc61))) -> tensor<?xf32> {
    return %arg2 : tensor<?xf32> loc(#loc79)
  } loc(#loc79)
  func.func private @_where_1(%arg0: tensor<i32> {jax.global_constant = "graph_max_neighbors", mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue, UnspecifiedValue) in_layouts=(None, None, None) out_layouts=(None, None) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61)), %arg1: tensor<i32> {jax.global_constant = "n_atoms", mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue, UnspecifiedValue) in_layouts=(None, None, None) out_layouts=(None, None) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61)), %arg2: tensor<?xi1> {mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue, UnspecifiedValue) in_layouts=(None, None, None) out_layouts=(None, None) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61)), %arg3: tensor<?xf32> {mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue, UnspecifiedValue) in_layouts=(None, None, None) out_layouts=(None, None) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61)), %arg4: tensor<i32> {mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue, UnspecifiedValue) in_layouts=(None, None, None) out_layouts=(None, None) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61))) -> (tensor<?xf32> {mhlo.layout_mode = "default"}, tensor<?xf32> {mhlo.layout_mode = "default"}) {
    %0 = stablehlo.convert %arg4 : (tensor<i32>) -> tensor<f32> loc(#loc110)
    %1 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc111)
    %2 = stablehlo.dynamic_broadcast_in_dim %0, %1, dims = [] : (tensor<f32>, tensor<1xi32>) -> tensor<?xf32> loc(#loc111)
    %3 = stablehlo.select %arg2, %arg3, %2 : tensor<?xi1>, tensor<?xf32> loc(#loc112)
    %cst = stablehlo.constant dense<0.000000e+00> : tensor<f32> loc(#loc88)
    %4 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc111)
    %5 = stablehlo.dynamic_broadcast_in_dim %cst, %4, dims = [] : (tensor<f32>, tensor<1xi32>) -> tensor<?xf32> loc(#loc111)
    return %3, %5 : tensor<?xf32>, tensor<?xf32> loc(#loc88)
  } loc(#loc88)
  func.func private @_where_2(%arg0: tensor<i32> {jax.global_constant = "graph_max_neighbors", mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue, UnspecifiedValue) in_layouts=(None, None, None) out_layouts=(None, None) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61)), %arg1: tensor<i32> {jax.global_constant = "n_atoms", mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue, UnspecifiedValue) in_layouts=(None, None, None) out_layouts=(None, None) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61)), %arg2: tensor<?xi1> {mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue, UnspecifiedValue) in_layouts=(None, None, None) out_layouts=(None, None) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61)), %arg3: tensor<i32> {mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue, UnspecifiedValue) in_layouts=(None, None, None) out_layouts=(None, None) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61)), %arg4: tensor<?xf32> {mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue, UnspecifiedValue) in_layouts=(None, None, None) out_layouts=(None, None) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61))) -> (tensor<?xf32> {mhlo.layout_mode = "default"}, tensor<?xf32> {mhlo.layout_mode = "default"}) {
    %0 = stablehlo.convert %arg3 : (tensor<i32>) -> tensor<f32> loc(#loc110)
    %1 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc111)
    %2 = stablehlo.dynamic_broadcast_in_dim %0, %1, dims = [] : (tensor<f32>, tensor<1xi32>) -> tensor<?xf32> loc(#loc111)
    %3 = stablehlo.select %arg2, %2, %arg4 : tensor<?xi1>, tensor<?xf32> loc(#loc112)
    %cst = stablehlo.constant dense<0.000000e+00> : tensor<f32> loc(#loc88)
    %4 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc111)
    %5 = stablehlo.dynamic_broadcast_in_dim %cst, %4, dims = [] : (tensor<f32>, tensor<1xi32>) -> tensor<?xf32> loc(#loc111)
    return %3, %5 : tensor<?xf32>, tensor<?xf32> loc(#loc88)
  } loc(#loc88)
  func.func private @integer_pow_3(%arg0: tensor<i32> loc("jit(_energy_fn)/jit(main)/integer_pow[y=-2]"(#loc61)), %arg1: tensor<i32> loc("jit(_energy_fn)/jit(main)/integer_pow[y=-2]"(#loc61)), %arg2: tensor<?xf32> loc("jit(_energy_fn)/jit(main)/integer_pow[y=-2]"(#loc61))) -> tensor<?xf32> {
    %0 = stablehlo.multiply %arg2, %arg2 : tensor<?xf32> loc(#loc80)
    %cst = stablehlo.constant dense<1.000000e+00> : tensor<f32> loc(#loc89)
    %1 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc93)
    %2 = stablehlo.dynamic_broadcast_in_dim %cst, %1, dims = [] : (tensor<f32>, tensor<1xi32>) -> tensor<?xf32> loc(#loc93)
    %3 = stablehlo.divide %2, %0 : tensor<?xf32> loc(#loc87)
    return %3 : tensor<?xf32> loc(#loc89)
  } loc(#loc89)
  func.func private @nan_to_num(%arg0: tensor<i32> {jax.global_constant = "graph_max_neighbors", mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue,) out_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) in_layouts=(None,) out_layouts=(None, None, None, None, None, None, None) resource_env=None donated_invars=(False,) name=nan_to_num keep_unused=False inline=False]"(#loc61)), %arg1: tensor<i32> {jax.global_constant = "n_atoms", mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue,) out_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) in_layouts=(None,) out_layouts=(None, None, None, None, None, None, None) resource_env=None donated_invars=(False,) name=nan_to_num keep_unused=False inline=False]"(#loc61)), %arg2: tensor<?xf32> {mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue,) out_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) in_layouts=(None,) out_layouts=(None, None, None, None, None, None, None) resource_env=None donated_invars=(False,) name=nan_to_num keep_unused=False inline=False]"(#loc61))) -> (tensor<?xf32> {mhlo.layout_mode = "default"}, tensor<?xi1> {mhlo.layout_mode = "default"}, tensor<?xf32> {mhlo.layout_mode = "default"}, tensor<?xi1> {mhlo.layout_mode = "default"}, tensor<?xf32> {mhlo.layout_mode = "default"}, tensor<?xi1> {mhlo.layout_mode = "default"}, tensor<?xf32> {mhlo.layout_mode = "default"}) {
    %0 = stablehlo.compare  NE, %arg2, %arg2,  FLOAT : (tensor<?xf32>, tensor<?xf32>) -> tensor<?xi1> loc(#loc113)
    %cst = stablehlo.constant dense<0.000000e+00> : tensor<f32> loc(#loc90)
    %1:2 = call @_where_4(%arg0, %arg1, %0, %cst, %arg2) : (tensor<i32>, tensor<i32>, tensor<?xi1>, tensor<f32>, tensor<?xf32>) -> (tensor<?xf32>, tensor<?xf32>) loc(#loc114)
    %cst_0 = stablehlo.constant dense<0x7F800000> : tensor<f32> loc(#loc90)
    %2 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc115)
    %3 = stablehlo.dynamic_broadcast_in_dim %cst_0, %2, dims = [] : (tensor<f32>, tensor<1xi32>) -> tensor<?xf32> loc(#loc115)
    %4 = stablehlo.compare  EQ, %1#0, %3,  FLOAT : (tensor<?xf32>, tensor<?xf32>) -> tensor<?xi1> loc(#loc115)
    %cst_1 = stablehlo.constant dense<3.40282347E+38> : tensor<f32> loc(#loc90)
    %5:2 = call @_where_4(%arg0, %arg1, %4, %cst_1, %1#0) : (tensor<i32>, tensor<i32>, tensor<?xi1>, tensor<f32>, tensor<?xf32>) -> (tensor<?xf32>, tensor<?xf32>) loc(#loc114)
    %cst_2 = stablehlo.constant dense<0xFF800000> : tensor<f32> loc(#loc90)
    %6 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc115)
    %7 = stablehlo.dynamic_broadcast_in_dim %cst_2, %6, dims = [] : (tensor<f32>, tensor<1xi32>) -> tensor<?xf32> loc(#loc115)
    %8 = stablehlo.compare  EQ, %5#0, %7,  FLOAT : (tensor<?xf32>, tensor<?xf32>) -> tensor<?xi1> loc(#loc115)
    %cst_3 = stablehlo.constant dense<-3.40282347E+38> : tensor<f32> loc(#loc90)
    %9:2 = call @_where_4(%arg0, %arg1, %8, %cst_3, %5#0) : (tensor<i32>, tensor<i32>, tensor<?xi1>, tensor<f32>, tensor<?xf32>) -> (tensor<?xf32>, tensor<?xf32>) loc(#loc114)
    return %9#0, %0, %1#1, %4, %5#1, %8, %9#1 : tensor<?xf32>, tensor<?xi1>, tensor<?xf32>, tensor<?xi1>, tensor<?xf32>, tensor<?xi1>, tensor<?xf32> loc(#loc90)
  } loc(#loc90)
  func.func private @_where_4(%arg0: tensor<i32> {jax.global_constant = "graph_max_neighbors", mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/jvp(jit(nan_to_num))/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue, UnspecifiedValue) in_layouts=(None, None, None) out_layouts=(None, None) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61)), %arg1: tensor<i32> {jax.global_constant = "n_atoms", mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/jvp(jit(nan_to_num))/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue, UnspecifiedValue) in_layouts=(None, None, None) out_layouts=(None, None) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61)), %arg2: tensor<?xi1> {mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/jvp(jit(nan_to_num))/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue, UnspecifiedValue) in_layouts=(None, None, None) out_layouts=(None, None) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61)), %arg3: tensor<f32> {mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/jvp(jit(nan_to_num))/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue, UnspecifiedValue) in_layouts=(None, None, None) out_layouts=(None, None) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61)), %arg4: tensor<?xf32> {mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/jvp(jit(nan_to_num))/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue, UnspecifiedValue) in_layouts=(None, None, None) out_layouts=(None, None) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61))) -> (tensor<?xf32> {mhlo.layout_mode = "default"}, tensor<?xf32> {mhlo.layout_mode = "default"}) {
    %0 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc116)
    %1 = stablehlo.dynamic_broadcast_in_dim %arg3, %0, dims = [] : (tensor<f32>, tensor<1xi32>) -> tensor<?xf32> loc(#loc116)
    %2 = stablehlo.select %arg2, %1, %arg4 : tensor<?xi1>, tensor<?xf32> loc(#loc117)
    %cst = stablehlo.constant dense<0.000000e+00> : tensor<f32> loc(#loc114)
    %3 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc116)
    %4 = stablehlo.dynamic_broadcast_in_dim %cst, %3, dims = [] : (tensor<f32>, tensor<1xi32>) -> tensor<?xf32> loc(#loc116)
    return %2, %4 : tensor<?xf32>, tensor<?xf32> loc(#loc114)
  } loc(#loc114)
  func.func private @nan_to_num_5(%arg0: tensor<i32> {jax.global_constant = "graph_max_neighbors", mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue,) in_layouts=(None, None, None, None, None, None, None) out_layouts=(None,) resource_env=None donated_invars=(False, False, False, False, False, False, False) name=nan_to_num keep_unused=False inline=False]"(#loc61)), %arg1: tensor<i32> {jax.global_constant = "n_atoms", mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue,) in_layouts=(None, None, None, None, None, None, None) out_layouts=(None,) resource_env=None donated_invars=(False, False, False, False, False, False, False) name=nan_to_num keep_unused=False inline=False]"(#loc61)), %arg2: tensor<?xi1> {mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue,) in_layouts=(None, None, None, None, None, None, None) out_layouts=(None,) resource_env=None donated_invars=(False, False, False, False, False, False, False) name=nan_to_num keep_unused=False inline=False]"(#loc61)), %arg3: tensor<?xf32> {mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue,) in_layouts=(None, None, None, None, None, None, None) out_layouts=(None,) resource_env=None donated_invars=(False, False, False, False, False, False, False) name=nan_to_num keep_unused=False inline=False]"(#loc61)), %arg4: tensor<?xi1> {mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue,) in_layouts=(None, None, None, None, None, None, None) out_layouts=(None,) resource_env=None donated_invars=(False, False, False, False, False, False, False) name=nan_to_num keep_unused=False inline=False]"(#loc61)), %arg5: tensor<?xf32> {mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue,) in_layouts=(None, None, None, None, None, None, None) out_layouts=(None,) resource_env=None donated_invars=(False, False, False, False, False, False, False) name=nan_to_num keep_unused=False inline=False]"(#loc61)), %arg6: tensor<?xi1> {mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue,) in_layouts=(None, None, None, None, None, None, None) out_layouts=(None,) resource_env=None donated_invars=(False, False, False, False, False, False, False) name=nan_to_num keep_unused=False inline=False]"(#loc61)), %arg7: tensor<?xf32> {mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue,) in_layouts=(None, None, None, None, None, None, None) out_layouts=(None,) resource_env=None donated_invars=(False, False, False, False, False, False, False) name=nan_to_num keep_unused=False inline=False]"(#loc61)), %arg8: tensor<?xf32> {mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue,) in_layouts=(None, None, None, None, None, None, None) out_layouts=(None,) resource_env=None donated_invars=(False, False, False, False, False, False, False) name=nan_to_num keep_unused=False inline=False]"(#loc61))) -> (tensor<?xf32> {mhlo.layout_mode = "default"}) {
    %0 = call @_where_6(%arg0, %arg1, %arg6, %arg7, %arg8) : (tensor<i32>, tensor<i32>, tensor<?xi1>, tensor<?xf32>, tensor<?xf32>) -> tensor<?xf32> loc(#loc118)
    %1 = call @_where_6(%arg0, %arg1, %arg4, %arg5, %0) : (tensor<i32>, tensor<i32>, tensor<?xi1>, tensor<?xf32>, tensor<?xf32>) -> tensor<?xf32> loc(#loc118)
    %2 = call @_where_6(%arg0, %arg1, %arg2, %arg3, %1) : (tensor<i32>, tensor<i32>, tensor<?xi1>, tensor<?xf32>, tensor<?xf32>) -> tensor<?xf32> loc(#loc118)
    return %2 : tensor<?xf32> loc(#loc94)
  } loc(#loc94)
  func.func private @_where_6(%arg0: tensor<i32> {jax.global_constant = "graph_max_neighbors", mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/transpose(jvp(jit(nan_to_num)))/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue,) in_layouts=(None, None, None) out_layouts=(None,) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61)), %arg1: tensor<i32> {jax.global_constant = "n_atoms", mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/transpose(jvp(jit(nan_to_num)))/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue,) in_layouts=(None, None, None) out_layouts=(None,) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61)), %arg2: tensor<?xi1> {mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/transpose(jvp(jit(nan_to_num)))/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue,) in_layouts=(None, None, None) out_layouts=(None,) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61)), %arg3: tensor<?xf32> {mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/transpose(jvp(jit(nan_to_num)))/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue,) in_layouts=(None, None, None) out_layouts=(None,) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61)), %arg4: tensor<?xf32> {mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/transpose(jvp(jit(nan_to_num)))/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue,) in_layouts=(None, None, None) out_layouts=(None,) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61))) -> (tensor<?xf32> {mhlo.layout_mode = "default"}) {
    %cst = stablehlo.constant dense<0.000000e+00> : tensor<f32> loc(#loc118)
    %0 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc119)
    %1 = stablehlo.dynamic_broadcast_in_dim %cst, %0, dims = [] : (tensor<f32>, tensor<1xi32>) -> tensor<?xf32> loc(#loc119)
    %2 = stablehlo.select %arg2, %1, %arg4 : tensor<?xi1>, tensor<?xf32> loc(#loc120)
    return %2 : tensor<?xf32> loc(#loc118)
  } loc(#loc118)
  func.func private @_where_7(%arg0: tensor<i32> {jax.global_constant = "graph_max_neighbors", mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue,) in_layouts=(None, None, None) out_layouts=(None,) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61)), %arg1: tensor<i32> {jax.global_constant = "n_atoms", mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue,) in_layouts=(None, None, None) out_layouts=(None,) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61)), %arg2: tensor<?xi1> {mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue,) in_layouts=(None, None, None) out_layouts=(None,) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61)), %arg3: tensor<?xf32> {mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue,) in_layouts=(None, None, None) out_layouts=(None,) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61)), %arg4: tensor<?xf32> {mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue,) in_layouts=(None, None, None) out_layouts=(None,) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61))) -> (tensor<?xf32> {mhlo.layout_mode = "default"}) {
    %cst = stablehlo.constant dense<0.000000e+00> : tensor<f32> loc(#loc97)
    %0 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc121)
    %1 = stablehlo.dynamic_broadcast_in_dim %cst, %0, dims = [] : (tensor<f32>, tensor<1xi32>) -> tensor<?xf32> loc(#loc121)
    %2 = stablehlo.select %arg2, %1, %arg4 : tensor<?xi1>, tensor<?xf32> loc(#loc122)
    return %2 : tensor<?xf32> loc(#loc97)
  } loc(#loc97)
  func.func private @_where_8(%arg0: tensor<i32> {jax.global_constant = "graph_max_neighbors", mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue,) in_layouts=(None, None, None) out_layouts=(None,) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61)), %arg1: tensor<i32> {jax.global_constant = "n_atoms", mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue,) in_layouts=(None, None, None) out_layouts=(None,) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61)), %arg2: tensor<?xi1> {mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue,) in_layouts=(None, None, None) out_layouts=(None,) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61)), %arg3: tensor<?xf32> {mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue,) in_layouts=(None, None, None) out_layouts=(None,) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61)), %arg4: tensor<?xf32> {mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue,) in_layouts=(None, None, None) out_layouts=(None,) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61))) -> (tensor<?xf32> {mhlo.layout_mode = "default"}) {
    %cst = stablehlo.constant dense<0.000000e+00> : tensor<f32> loc(#loc97)
    %0 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc121)
    %1 = stablehlo.dynamic_broadcast_in_dim %cst, %0, dims = [] : (tensor<f32>, tensor<1xi32>) -> tensor<?xf32> loc(#loc121)
    %2 = stablehlo.select %arg2, %arg4, %1 : tensor<?xi1>, tensor<?xf32> loc(#loc122)
    return %2 : tensor<?xf32> loc(#loc97)
  } loc(#loc97)
  func.func private @safe_mask_9(%arg0: tensor<i32> {jax.global_constant = "graph_max_neighbors", mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue,) in_layouts=(None, None, None, None, None) out_layouts=(None,) resource_env=None donated_invars=(False, False, False, False, False) name=safe_mask keep_unused=False inline=False]"(#loc61)), %arg1: tensor<i32> {jax.global_constant = "n_atoms", mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue,) in_layouts=(None, None, None, None, None) out_layouts=(None,) resource_env=None donated_invars=(False, False, False, False, False) name=safe_mask keep_unused=False inline=False]"(#loc61)), %arg2: tensor<?xi1> {mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue,) in_layouts=(None, None, None, None, None) out_layouts=(None,) resource_env=None donated_invars=(False, False, False, False, False) name=safe_mask keep_unused=False inline=False]"(#loc61)), %arg3: tensor<?xf32> {mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue,) in_layouts=(None, None, None, None, None) out_layouts=(None,) resource_env=None donated_invars=(False, False, False, False, False) name=safe_mask keep_unused=False inline=False]"(#loc61)), %arg4: tensor<?xf32> {mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue,) in_layouts=(None, None, None, None, None) out_layouts=(None,) resource_env=None donated_invars=(False, False, False, False, False) name=safe_mask keep_unused=False inline=False]"(#loc61)), %arg5: tensor<?xf32> {mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue,) in_layouts=(None, None, None, None, None) out_layouts=(None,) resource_env=None donated_invars=(False, False, False, False, False) name=safe_mask keep_unused=False inline=False]"(#loc61)), %arg6: tensor<?xf32> {mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue,) in_layouts=(None, None, None, None, None) out_layouts=(None,) resource_env=None donated_invars=(False, False, False, False, False) name=safe_mask keep_unused=False inline=False]"(#loc61))) -> (tensor<?xf32> {mhlo.layout_mode = "default"}) {
    %0 = call @_where_10(%arg0, %arg1, %arg2, %arg5, %arg6) : (tensor<i32>, tensor<i32>, tensor<?xi1>, tensor<?xf32>, tensor<?xf32>) -> tensor<?xf32> loc(#loc123)
    %1 = stablehlo.multiply %0, %arg4 : tensor<?xf32> loc(#loc124)
    %2 = call @_where_10(%arg0, %arg1, %arg2, %arg3, %1) : (tensor<i32>, tensor<i32>, tensor<?xi1>, tensor<?xf32>, tensor<?xf32>) -> tensor<?xf32> loc(#loc123)
    return %2 : tensor<?xf32> loc(#loc98)
  } loc(#loc98)
  func.func private @_where_10(%arg0: tensor<i32> {jax.global_constant = "graph_max_neighbors", mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/transpose(jvp(vmap(jit(safe_mask))))/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue,) in_layouts=(None, None, None) out_layouts=(None,) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61)), %arg1: tensor<i32> {jax.global_constant = "n_atoms", mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/transpose(jvp(vmap(jit(safe_mask))))/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue,) in_layouts=(None, None, None) out_layouts=(None,) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61)), %arg2: tensor<?xi1> {mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/transpose(jvp(vmap(jit(safe_mask))))/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue,) in_layouts=(None, None, None) out_layouts=(None,) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61)), %arg3: tensor<?xf32> {mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/transpose(jvp(vmap(jit(safe_mask))))/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue,) in_layouts=(None, None, None) out_layouts=(None,) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61)), %arg4: tensor<?xf32> {mhlo.layout_mode = "default"} loc("jit(_energy_fn)/jit(main)/transpose(jvp(vmap(jit(safe_mask))))/pjit[in_shardings=(UnspecifiedValue, UnspecifiedValue, UnspecifiedValue) out_shardings=(UnspecifiedValue,) in_layouts=(None, None, None) out_layouts=(None,) resource_env=None donated_invars=(False, False, False) name=_where keep_unused=False inline=False]"(#loc61))) -> (tensor<?xf32> {mhlo.layout_mode = "default"}) {
    %cst = stablehlo.constant dense<0.000000e+00> : tensor<f32> loc(#loc123)
    %0 = stablehlo.reshape %arg0 : (tensor<i32>) -> tensor<1xi32> loc(#loc125)
    %1 = stablehlo.dynamic_broadcast_in_dim %cst, %0, dims = [] : (tensor<f32>, tensor<1xi32>) -> tensor<?xf32> loc(#loc125)
    %2 = stablehlo.select %arg2, %arg4, %1 : tensor<?xi1>, tensor<?xf32> loc(#loc126)
    return %2 : tensor<?xf32> loc(#loc123)
  } loc(#loc123)
} loc(#loc)
#loc9 = loc("/Users/paul/Lokal/Software/chemtrain-dev/examples/lennard_jones/export.py":44:16)
#loc11 = loc("/Users/paul/Lokal/Software/chemtrain-dev/jax_md_mod/custom_energy.py":557:8)
#loc12 = loc("/Users/paul/Lokal/Software/chemtrain-dev/examples/lennard_jones/export.py":59:23)
#loc14 = loc("/Users/paul/Lokal/Software/chemtrain-dev/examples/lennard_jones/export.py":60:41)
#loc15 = loc("/Users/paul/Lokal/Software/chemtrain-dev/chemtrain/deploy/exporter.py":103:16)
#loc16 = loc("/Users/paul/Lokal/Software/chemtrain-dev/chemtrain/deploy/exporter.py":103:15)
#loc17 = loc("/Users/paul/Lokal/Software/chemtrain-dev/chemtrain/deploy/exporter.py":103:44)
#loc18 = loc("<frozen importlib._bootstrap>":241:11)
#loc19 = loc("<frozen importlib._bootstrap_external>":940:8)
#loc20 = loc("<frozen importlib._bootstrap>":690:16)
#loc21 = loc("<frozen importlib._bootstrap>":1147:21)
#loc22 = loc("<frozen importlib._bootstrap>":1176:23)
#loc23 = loc("<frozen importlib._bootstrap>":1232:16)
#loc27 = loc("build_export_model.<locals>.LennardJonesExport.energy_fn"(#loc9))
#loc29 = loc("customn_lennard_jones_neighbor_list"(#loc11))
#loc30 = loc("build_export_model.<locals>.LennardJonesExport.energy_fn"(#loc12))
#loc32 = loc("build_export_model.<locals>.LennardJonesExport.energy_fn.<locals>.<lambda>"(#loc14))
#loc33 = loc("Exporter._energy_fn"(#loc15))
#loc34 = loc("Exporter._energy_fn"(#loc16))
#loc35 = loc("Exporter._energy_fn"(#loc17))
#loc36 = loc("_call_with_frames_removed"(#loc18))
#loc37 = loc("_LoaderBasics.exec_module"(#loc19))
#loc38 = loc("_load_unlocked"(#loc20))
#loc39 = loc("_find_and_load_unlocked"(#loc21))
#loc40 = loc("_find_and_load"(#loc22))
#loc41 = loc("_handle_fromlist"(#loc23))
#loc43 = loc(callsite(#loc37 at #loc38))
#loc45 = loc(callsite(#loc36 at #loc43))
#loc46 = loc("/dimension_size[dimension=0]"(#loc44))
#loc47 = loc("/ge"(#loc44))
#loc48 = loc("/shape_assertion[error_message=Input shapes do not match the polymorphic shapes specification. Expected value >= 1 for dimension variable 'n_atoms'. Using the following polymorphic shapes specifications: args[0].shape = (n_atoms, 3),args[1].shape = (n_atoms,),args[2].shape = (n_atoms,),args[3].shape = (graph_max_neighbors,),args[4].shape = (graph_max_neighbors,). Obtained dimension variables: 'n_atoms' = {0} from specification 'n_atoms' for dimension args[0].shape[0] (= {0}), . Please see https://jax.readthedocs.io/en/latest/export/shape_poly.html#shape-assertion-errors for more details.]"(#loc44))
#loc49 = loc("/eq"(#loc44))
#loc50 = loc("/shape_assertion[error_message=Input shapes do not match the polymorphic shapes specification. Found inconsistency between dimension size args[1].shape[0] (= {0}) and the specification 'n_atoms' (= {1}). Using the following polymorphic shapes specifications: args[0].shape = (n_atoms, 3),args[1].shape = (n_atoms,),args[2].shape = (n_atoms,),args[3].shape = (graph_max_neighbors,),args[4].shape = (graph_max_neighbors,). Obtained dimension variables: 'n_atoms' = {1} from specification 'n_atoms' for dimension args[0].shape[0] (= {1}), . Please see https://jax.readthedocs.io/en/latest/export/shape_poly.html#shape-assertion-errors for more details.]"(#loc44))
#loc51 = loc("/shape_assertion[error_message=Input shapes do not match the polymorphic shapes specification. Found inconsistency between dimension size args[2].shape[0] (= {0}) and the specification 'n_atoms' (= {1}). Using the following polymorphic shapes specifications: args[0].shape = (n_atoms, 3),args[1].shape = (n_atoms,),args[2].shape = (n_atoms,),args[3].shape = (graph_max_neighbors,),args[4].shape = (graph_max_neighbors,). Obtained dimension variables: 'n_atoms' = {1} from specification 'n_atoms' for dimension args[0].shape[0] (= {1}), . Please see https://jax.readthedocs.io/en/latest/export/shape_poly.html#shape-assertion-errors for more details.]"(#loc44))
#loc52 = loc("/shape_assertion[error_message=Input shapes do not match the polymorphic shapes specification. Expected value >= 1 for dimension variable 'graph_max_neighbors'. Using the following polymorphic shapes specifications: args[0].shape = (n_atoms, 3),args[1].shape = (n_atoms,),args[2].shape = (n_atoms,),args[3].shape = (graph_max_neighbors,),args[4].shape = (graph_max_neighbors,). Obtained dimension variables: 'n_atoms' = {0} from specification 'n_atoms' for dimension args[0].shape[0] (= {0}), 'graph_max_neighbors' = {1} from specification 'graph_max_neighbors' for dimension args[3].shape[0] (= {1}), . Please see https://jax.readthedocs.io/en/latest/export/shape_poly.html#shape-assertion-errors for more details.]"(#loc44))
#loc53 = loc("/shape_assertion[error_message=Input shapes do not match the polymorphic shapes specification. Found inconsistency between dimension size args[4].shape[0] (= {0}) and the specification 'graph_max_neighbors' (= {1}). Using the following polymorphic shapes specifications: args[0].shape = (n_atoms, 3),args[1].shape = (n_atoms,),args[2].shape = (n_atoms,),args[3].shape = (graph_max_neighbors,),args[4].shape = (graph_max_neighbors,). Obtained dimension variables: 'n_atoms' = {2} from specification 'n_atoms' for dimension args[0].shape[0] (= {2}), 'graph_max_neighbors' = {1} from specification 'graph_max_neighbors' for dimension args[3].shape[0] (= {1}), . Please see https://jax.readthedocs.io/en/latest/export/shape_poly.html#shape-assertion-errors for more details.]"(#loc44))
#loc55 = loc(callsite(#loc33 at #loc44))
#loc56 = loc(callsite(#loc34 at #loc44))
#loc57 = loc(callsite(#loc35 at #loc44))
#loc58 = loc(callsite(#loc41 at #loc45))
#loc59 = loc(callsite(#loc27 at #loc54))
#loc60 = loc(callsite(#loc30 at #loc54))
#loc62 = loc("jit(_energy_fn)/jit(main)/reduce_sum[axes=()]"(#loc55))
#loc63 = loc("jit(_energy_fn)/jit(main)/neg"(#loc56))
#loc64 = loc("jit(_energy_fn)/jit(main)/reduce_sum[axes=()]"(#loc57))
#loc65 = loc(callsite(#loc36 at #loc58))
#loc66 = loc("jit(_energy_fn)/jit(main)/broadcast_in_dim[shape=(1, graph_max_neighbors) broadcast_dimensions=(1,)]"(#loc59))
#loc67 = loc("jit(_energy_fn)/jit(main)/concatenate[dimension=0]"(#loc59))
#loc68 = loc(callsite(#loc29 at #loc60))
#loc69 = loc("jit(_energy_fn)/jit(main)/broadcast_in_dim[shape=(1,) broadcast_dimensions=()]"(#loc61))
#loc70 = loc("jit(_energy_fn)/jit(main)/gather[dimension_numbers=GatherDimensionNumbers(offset_dims=(0,), collapsed_slice_dims=(0,), start_index_map=(0,)) slice_sizes=(1, graph_max_neighbors) unique_indices=True indices_are_sorted=True mode=GatherScatterMode.PROMISE_IN_BOUNDS fill_value=None]"(#loc61))
#loc71 = loc("jit(_energy_fn)/jit(main)/convert_element_type[new_dtype=int32 weak_type=False]"(#loc61))
#loc72 = loc("jit(_energy_fn)/jit(main)/lt"(#loc61))
#loc73 = loc("jit(_energy_fn)/jit(main)/add"(#loc61))
#loc74 = loc("jit(_energy_fn)/jit(main)/select_n"(#loc61))
#loc75 = loc("jit(_energy_fn)/jit(main)/broadcast_in_dim[shape=(graph_max_neighbors, 1) broadcast_dimensions=(0,)]"(#loc61))
#loc76 = loc("jit(_energy_fn)/jit(main)/gather[dimension_numbers=GatherDimensionNumbers(offset_dims=(1,), collapsed_slice_dims=(0,), start_index_map=(0,)) slice_sizes=(1, 3) unique_indices=False indices_are_sorted=False mode=GatherScatterMode.PROMISE_IN_BOUNDS fill_value=None]"(#loc61))
#loc77 = loc(callsite(#loc32 at #loc61))
#loc78 = loc("jit(_energy_fn)/jit(main)/integer_pow[y=2]"(#loc61))
#loc80 = loc("jit(_energy_fn)/jit(main)/mul"(#loc61))
#loc81 = loc("jit(_energy_fn)/jit(main)/reduce_sum[axes=(1,)]"(#loc61))
#loc82 = loc("jit(_energy_fn)/jit(main)/gt"(#loc61))
#loc84 = loc("jit(_energy_fn)/jit(main)/pow"(#loc61))
#loc85 = loc("jit(_energy_fn)/jit(main)/sub"(#loc61))
#loc86 = loc("jit(_energy_fn)/jit(main)/integer_pow[y=3]"(#loc61))
#loc87 = loc("jit(_energy_fn)/jit(main)/div"(#loc61))
#loc91 = loc("jit(_energy_fn)/jit(main)/convert_element_type[new_dtype=float32 weak_type=False]"(#loc61))
#loc92 = loc("jit(_energy_fn)/jit(main)/reduce_sum[axes=(0,)]"(#loc61))
#loc93 = loc("jit(_energy_fn)/jit(main)/broadcast_in_dim[shape=(graph_max_neighbors,) broadcast_dimensions=()]"(#loc61))
#loc95 = loc("jit(_energy_fn)/jit(main)/neg"(#loc61))
#loc96 = loc("jit(_energy_fn)/jit(main)/add_any"(#loc61))
#loc99 = loc("jit(_energy_fn)/jit(main)/broadcast_in_dim[shape=(graph_max_neighbors, 3) broadcast_dimensions=(0,)]"(#loc61))
#loc100 = loc("jit(_energy_fn)/jit(main)/reduce_sum[axes=()]"(#loc61))
#loc101 = loc("jit(_energy_fn)/jit(main)/broadcast_in_dim[shape=(n_atoms, 3) broadcast_dimensions=()]"(#loc61))
#loc103 = loc(callsite(#loc40 at #loc65))
#loc105 = loc("jit(_energy_fn)/jit(main)/jvp(vmap(jit(safe_mask)))/sqrt"(#loc61))
#loc106 = loc("jit(_energy_fn)/jit(main)/jvp(vmap(jit(safe_mask)))/div"(#loc61))
#loc107 = loc("jit(_energy_fn)/jit(main)/jvp(vmap(jit(safe_mask)))/jit(_where)/convert_element_type[new_dtype=float32 weak_type=False]"(#loc61))
#loc108 = loc("jit(_energy_fn)/jit(main)/jvp(vmap(jit(safe_mask)))/jit(_where)/broadcast_in_dim[shape=(graph_max_neighbors,) broadcast_dimensions=()]"(#loc61))
#loc109 = loc("jit(_energy_fn)/jit(main)/jvp(vmap(jit(safe_mask)))/jit(_where)/select_n"(#loc61))
#loc110 = loc("jit(_energy_fn)/jit(main)/jvp(jit(_where))/convert_element_type[new_dtype=float32 weak_type=False]"(#loc61))
#loc111 = loc("jit(_energy_fn)/jit(main)/jvp(jit(_where))/broadcast_in_dim[shape=(graph_max_neighbors,) broadcast_dimensions=()]"(#loc61))
#loc112 = loc("jit(_energy_fn)/jit(main)/jvp(jit(_where))/select_n"(#loc61))
#loc113 = loc("jit(_energy_fn)/jit(main)/jvp(jit(nan_to_num))/ne"(#loc61))
#loc115 = loc("jit(_energy_fn)/jit(main)/jvp(jit(nan_to_num))/eq"(#loc61))
#loc116 = loc("jit(_energy_fn)/jit(main)/jvp(jit(nan_to_num))/jit(_where)/broadcast_in_dim[shape=(graph_max_neighbors,) broadcast_dimensions=()]"(#loc61))
#loc117 = loc("jit(_energy_fn)/jit(main)/jvp(jit(nan_to_num))/jit(_where)/select_n"(#loc61))
#loc119 = loc("jit(_energy_fn)/jit(main)/transpose(jvp(jit(nan_to_num)))/jit(_where)/broadcast_in_dim[shape=(graph_max_neighbors,) broadcast_dimensions=()]"(#loc61))
#loc120 = loc("jit(_energy_fn)/jit(main)/transpose(jvp(jit(nan_to_num)))/jit(_where)/select_n"(#loc61))
#loc121 = loc("jit(_energy_fn)/jit(main)/transpose(jvp(jit(_where)))/broadcast_in_dim[shape=(graph_max_neighbors,) broadcast_dimensions=()]"(#loc61))
#loc122 = loc("jit(_energy_fn)/jit(main)/transpose(jvp(jit(_where)))/select_n"(#loc61))
#loc124 = loc("jit(_energy_fn)/jit(main)/transpose(jvp(vmap(jit(safe_mask))))/mul"(#loc61))
#loc125 = loc("jit(_energy_fn)/jit(main)/transpose(jvp(vmap(jit(safe_mask))))/jit(_where)/broadcast_in_dim[shape=(graph_max_neighbors,) broadcast_dimensions=()]"(#loc61))
#loc126 = loc("jit(_energy_fn)/jit(main)/transpose(jvp(vmap(jit(safe_mask))))/jit(_where)/select_n"(#loc61))
#loc127 = loc("jit(_energy_fn)/jit(main)/pow"(#loc68))
#loc128 = loc("jit(_energy_fn)/jit(main)/sub"(#loc77))
#loc129 = loc("jit(_energy_fn)/jit(main)/neg"(#loc77))
#loc130 = loc(callsite(#loc39 at #loc103))
#loc131 = loc(callsite(#loc38 at #loc130))
#loc132 = loc(callsite(#loc37 at #loc131))
#loc133 = loc(callsite(#loc36 at #loc132))
#loc134 = loc("/add"(#loc133))
